spring:
  application:
    name: clinica-medica
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    community-db-support-enabled: true
    baseline-on-migrate: true
jwt:
    secret: ${JWT_SECRET:my_secret}