spring:
  application:
    name: clinica-medica-backend
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    community-db-support-enabled: true
    baseline-on-migrate: true
  threads:
    virtual:
      enabled: true
  main:
    keep-alive: true
jwt:
    secret: ${JWT_SECRET:my_secret}
resend:
  api-key: ${RESEND_API_KEY}
  from: ${RESEND_FROM}
app:
  cookie:
    domain: ${DOMINIO_URL:}